### PR TITLE
Fix terms; rewrite/fix old messages using zh-cn context

### PR DESCRIPTION
**Pull request by petercpg**
Next I'm going to deal with strings that should not be translated as well as add locale-specific comments(if needed), and try to build up glossaries in "translation references" folder :)

### CODE REVIEW

**Comment by ArmorDarks** [comment]
Hi

Thanks for PR!

I have to put it on hold for a while due to some strange issue with urls.

It seems that urls like

```
http://www.cfos.de/zh-tw/press/press.htm
```

in string

```
contact_form_l3 = "我們最新的 <a class=\"inline\" href=\"//zh-tw/press/press.htm\">新聞稿</a>";
```

doesn't fallback properly to other languages and redirects to index-page instead.

I will merge PR as soon as that issue will be resolved.

**Comment by petercpg** [comment]
Indeed. By the way, was the double slash in the path intended? I also find some entries have only one slash like:

```
upload_p1 = "請確保您有最新的 <a class=\"inline\" href=\"/zh-tw/download/download.htm\">預覽 (release)</a> 或 <a class=\"inline\" href=\"/zh-tw/beta/index.htm\">測試 (beta)</a> 版本。我們只能修正最新版本的問題。<br/><b>請不要上傳舊版本的錯誤傾印！</b>";
```

**Comment by ArmorDarks** [comment]
I've noticed double slashes too.  Though, those aren't related to escaping. Only left-aligned slash used for escaping, like `\\`.

Double slash in those urls seems to be more kind of mistype. However, don't bother with them. I will fix them later anyway — some other language might have them too.

Regarding mentioned by me issue with locales names in urls — it seems fixing will take some time.

During that time support recommended to change all urls to `/en/`. May I ask you to do so for zh-CN?

**Comment by petercpg** [comment]
I'm away on vacation and will be back in the weekend, will do when I came back to my PC.
Just want to make sure, you want me to change all `/zh-*/` back to `/en/`? No problem.

**Comment by ArmorDarks** [comment]
Oh :) I'll change them by myself then. No need to bother you with such things :)

I'm merging this PR then. Thanks!

I just wonder how do you manage to do so much work in such short terms...

If you'll to do at least basic Translation Reference for zh-TW — it would be really great.

If you're going to added locale-specific comments — remember that you should add them into English (1033) locale. They will be applied to all locales when I'll run them trough mltool automatically.

Usually most part of comments can be useful for all locales. But if you thinking about very-very specific comments, you may just add text which says that they are valid for zh-TW only. Or, alternatively, you can added comment after string in zh-TW locale, like this:

```
string = "zh-tw text"; /. Here is user comment
```

In such case there will be much less chances that those comments will be overridden by mltool during rebuilding ml-files.

Wish you great vacation :)

**Pull request merged**
