### PR TITLE
[website][tr] added translation by WildGenie

### PR DESCRIPTION
**Pull request by WildGenie**

### CODE REVIEW

**Comment by ArmorDarks** [comment]
Hi

Thanks a lot for new addition! :+1: 

Regarding this part:

> `// YTL to TL (2009), (Note:ISO 4217 code not changed), U+20BA TURKISH LIRA SIGN (₺) (MAY 2012) https://en.wikipedia.org/wiki/Turkish_lira`

Do you mean, that from now it's more appropriate to use TL suffix for Turkey? And am I right that it literally means same as YTL?

**Comment by WildGenie** [comment]
image
Web site using correct suffix.

**Comment by ArmorDarks** [comment]
Oh, hm, strange... seems like suffix isn't pulled from l10n files, but from somewhere else. I will check it out with our developers.

Few questions:

1. Just for the confirmation, do I understand that it would be better to use `LT` instead of `YLT`? And `₺` will be even better, right?
2. Is `₺` symbol popular and well known in Turkey? I'm asking, because in my country similar symbol for national currency exists for quite a while, but still not well known among citizens. In such case `LT` might be more preferable option.
3. `₺` should be placed before value, like `₺10`, is it correct?

**Comment by WildGenie** [comment]
1. **TL** is correct suffix now.
2. ₺ is not popular, now. But among citizens known. You are right **TL** might be more preferable option.
3. 10₺

**Comment by ArmorDarks** [comment]
Got it, thanks

> 10₺

That's a surpise. Seems that Wikipedia has an error?

zjwzfsa

**Comment by WildGenie** [comment]
image
This is my e-invoice.

And sorry, ₺10 is correct. "Left side and without space" 
image

**Comment by ArmorDarks** [comment]
Aha, got it, thanks!

I will fix `currency_suffix = "YTL";` string later by myself, as soon as Ingo will reply regarding where exactly it is used. Thanks for noticing this error :)

**Comment by WildGenie** [comment]
http://www.tcmb.gov.tr/wps/wcm/connect/tcmb+en/tcmb+en/bottom+menu/about+the+bank/faq#51

> On which side of the numerical figure will the Turkish lira sign be used?

> In line with international practice, the Turkish lira sign shall precede the numerical figure without a space.

**Comment by ArmorDarks** [comment]
Yeap, seems correct. Thanks.

For now we will continue to use `TL` on website, but if `₺` symbol will become more popular in Turkey, for sure we'll switch to it.

**Pull request merged**
