### PR TITLE
Update zh-tw translation for website parts

### PR DESCRIPTION
**Pull request by petercpg**
Not fully finished yet, but I think it's okay to merge for now.

### CODE REVIEW

**Comment by ArmorDarks** [comment]
That's what I call true massive update :) Thanks!

I've noticed that 5e76a6a48e2ab7833437e9592cf4e333f5f3e43c introduced some English strings and even blocks, like:

```
videos_h1 = "YouTube videos";
videos_text1 = "How to adjust the Medium/Protocol for your Internet connection";
videos_text2 = "cFos WMI Monitor, a cFos PNet add-on package";
videos_text3 = "cFos Personal Net Web Server | Installation and simple publishing";
videos_text4 = "cFosSpeed Automatic RWIN expansion feature keeps your CYGWIN SCP downloads fast";
videos_text5 = "cFosSpeed Automatic RWIN expansion feature keeps your Mozilla Firefox downloads fast";
videos_text6 = "cFosSpeed Automatic RWIN expansion feature keeps your Internet Explorer downloads fast";
videos_text7 = "cFosSpeed 7.0 - Temporary Prioritization of Connections";
videos_text8 = "cFosSpeed - Temporary Prioritization of Connections";
videos_text9 = "cFosSpeed 6.60 - How to calibrate your Internet connection";
videos_text10 = "cFosSpeed 6.60 - Keeps your Internet fast during upload/download - See how it works.";
videos_text11 = "cFosSpeed 6.60 - The Internet Accelerator ... faster Internet access with Traffic Shaping";
videos_text12 = "cFosSpeed 6.60 - How to register cFosSpeed with your personal license key file 'key.cfosspeed'";
videos_text13 = "cFosSpeed 6.60 - How to use Net Talk via the cFosSpeed console";
videos_text14 = "cFosSpeed with Logitech gaming keyboard G15";
videos_text15 = "cFosSpeed with Logitech gaming keyboard G19";
videos_text16 = "cFosSpeed 6.50 Installation on Windows7 32bit";
videos_text17 = "cFosSpeed Version 5.00 - Installation on Windows 7";
```

Does they should be like that?

**Comment by petercpg** [comment]
That block of translation was missing in the current translation so I added them as placeholder temporary for now, since they are not translated I think they won't change how users see the pages when merged. 

These strings will be fully translated in next commits, along with some zh-CN translations living inside zh-TW (e.g., speed test parts). 

Some minor amount of strings were intended to left blank, like:
<pre>cont_cont_p1 = "Information pursuant to TDG (German Tele Services Act): ";
cont_cont_p2 = "The service provider responsible for www.cfos.de and www.cfosspeed.de is the cFos Software GmbH, represented by owner-managers Christoph Lüders and Martin Winkler, Nordstr. 65a, 53111 Bonn, Phone: +49 2287669826, trade register entry: Bonn, HRB 9150; UStID / Vat-No.: DE813105998, eMail: .";</pre>
As these were German but not local law, it might probably better left untranslated? I will add translator's comment later.

**Comment by ArmorDarks** [comment]
There is really no need to copy English (base) strings into locale version, since thanks to our engine all missing strings will fallback during page building anyway.

In case of Traditional Chinese, if some string is missing, engine will look for translation in Simplified Chinese, and after if even there is no translation for current string in Simplified Chinese, it will fallback to English.

You can see fallback information in starting block of each locale:

```
#language 1028 \\ <- current language ID
#fallback 2052 \\ <- next language fallback ID (Simplified Chinese)
#fallback1 1033 \\ <- next language fallback ID (English)
#charset 136

/ **********************************************************************
/
/  language
/
/ **********************************************************************

language = "Traditional Chinese";

...
```

It also means that if some part intentionally should be left untranslated — just delete it from Traditional Chinese (or don't copy it there, as in your case).

**Comment by petercpg** [comment]
Yes but... my idea is when there is no comment added, others can't tell is it was a missing translation, or simply left untranslated intentionally. So I decided to add/change them all first, tag them with diff output, and remove them with a comment later. :)

Not sure it's worthy to make it distinguishable anyway.

**Comment by ArmorDarks** [comment]
Well, zh-TW section is completely up to you :)

So, you can choose workflow which fits best you.

Just remember to remove those sections later. And we also always have to consider possibility that might occur situation when we won't have time for further translation. In such situation, other translators might not understand for which purpose those strings where copied there.


And few other important thing, which you should know:

1. Usually if there is comment like `/ no translation`  before string or block — there is no need to translate as well as to copy it to locale's section

2. If there is no `/ no translation` comment before string, but it should be remained untranslated (like, let's say, `PayPal`) — it's better to copy explicitly that string to locale's section, as you did.

3. If there  is no `/ no translation` comment before string or block, but you think that it should be there — please, let me know, so we could decide it together.

  For example, in case of specified `cont_cont_p1` and `cont_cont_p2` strings there is no real reason to leave them untranslated. At least, no reason to copy them in locale's section. It won't hurt if they will remain English, as well as if they will be translated.

4. And **very** important thing about comment in general:

  Please, keep in mind that all comments always inherited from base language (English). If you'll write any comment in zh-TW section — it will be overridden while adding any other translation by our mltool.

  This means, that there is no need to copy comments from English section to locale manually — they will be inserted by mltool anyway. And if you want to leave specific for zh-TW section comment — it should be added to English section, with notation that it's valid only for zh-TW translations.

**Comment by ArmorDarks** [comment]
And thanks for commits! :)

**Pull request merged**
